name: CI build and Deploy

on:
  push:
    branches:
      - master
    tags:

env:
  CHANGE_MINIKUBE_NONE_USER: true
  INSTALL_K8S_TOOLS: 1
  IMG: kiwigrid/secret-replicator
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make

      - name: Build Docker
        run: make docker-build

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        k8s:
          # assume no breaking changes between the version
          - v1.12.10
          - v1.17.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: engineerd/setup-kind@v0.3.0
        with:
          config: .github/kind-config.yaml
          image: kindest/node:${{ matrix.k8s }}
      - name: Run tests
        env:
          TEST_EXTERNAL_KUBE: true
        run: make test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make

      - name: Build Docker
        run: make docker-build

      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: kiwigrid/secret-replicator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Tag to Registry
        if: contains(github.ref, 'refs/tags/v')
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: kiwigrid/secret-replicator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true